#######################
# Theme Customization #
#######################

title: Hanxue                             # used in <title> tag & site header
author: Hanxue Gu                        # used in a <meta> tag & /feed.xml
description: >                              # used in a <meta> tag & /feed.xml
 To record the everyday life of Fair Gu!
slogan: Fairly!                           # used in site header, beside title
avatar: /i/ghx.png                       # used as portrait in site header
banner: /i/mountains.svg                    # used as background in site header
url: http://solana.ryanlue.com              # used by plugins to generate feed.xml and sitemap.xml
baseurl: ''                                 # prepended to all absolute filepaths
repo: https://github.com/rlue/jekyll-solana # used in footer

# Objects listed here will appear in the main nav menu.
# Exceeding four items may cause problems on the desktop (>900px wide) layout.
nav_menu:
  - name: Posts
    url: /
    icon: /i/icons.svg#posts # icons should be 24x24 px.
  - name: Projects
    url: /projects
    icon: /i/icons.svg#portfolio
  - name: GitHub
    url: https://github.com/Guhanxue
    icon: /i/icons.svg#github
    outbound: true      # this key sets a link to open in a new window.
  - name: Contact
    scheme: mailto      # these keys enable email obfuscation.
    handle: hello       # you know, to protect you from bots. (handle and domain
    domain: github.com  # are separated in case bots crawl GitHub repos, too.)
    icon: /i/icons.svg#email

# Objects listed here will appear on the /projects.html page.
projects:
  - title: 3D-Hand Pose Reconstruction
    teaser: a Reconstruction system
    url: /
    role: Creator
    category: Computer vision
  - title: Breast Reconstruction
    teaser: need to develop
    url: /
    role: Core Team
    category: NLP


#################
# Site Settings #
#################

incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: listing  }
  - scope:  { type:   category }
    values: { layout: listing  }

sass:
  sass_dir: _assets/css

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 10
